// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

[TestFixture]
public class SemarkioUnitTestTest {

  public IWebDriver driver;

  public IDictionary<string, object> vars {get; private set;}

  public IJavaScriptExecutor js;

  [SetUp]

  public void SetUp() {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
  }

  [TearDown]
  protected void TearDown() {
        driver.Quit();
  }

  [Test]
  public void semarkioUnitTest() {
        // Abre site da Kabum
        driver.Navigate().GoToUrl("https://www.kabum.com.br/");
        driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);

        // Procura produto
        driver.FindElement(By.CssSelector(".sprocura")).Click();
        driver.FindElement(By.CssSelector(".sprocura")).SendKeys("placa de video");
        driver.FindElement(By.Id("bt-busca")).Click();

        // Verifica se foi encontrado na pesquisa
        bool isdisplaysearch = driver.FindElement(By.Id("Lamentamos, nenhum produto encontrado com esse critério de pesquisa")).Displayed;

        // Compra primeiro produto da lista
        driver.FindElement(By.CssSelector(".sc-fzqARJ:nth-child(3) .sc-AxhCb > img")).Click();

        // Verifica se foi adicionado ao carrinho
        bool isdisplaycheckout = driver.FindElement(By.Id("ESTE PRODUTO FOI ADICIONADO AO CARRINHO")).Displayed;

        // Vai para carrinho
        driver.FindElement(By.LinkText("IR PARA O CARRINHO")).Click();
  }
}
